### ISSUE TITLE
[BUG] Tooltip hides when icon within the button is hovered

### ISSUE THREAD

**Issue by jakub-w-sanoma** [sl-design-system/components#1347]
### Provide a general summary of the issue here

"@sl-design-system/tooltip": "1.0.1"

![tooltip is gone when button icon is hovered](https://github.com/sl-design-system/components/assets/93780154/e13e05e4-a29d-4e35-81b5-26b92e7ebfbb)

### 🤔 Expected Behavior?

Tooltip should be displayed when user hovers the icon within the button.

### 😯 Current Behavior

Tooltip that is set to sl-button hides when fa-icon placed inside is hovered.

### 🖥️ Steps to Reproduce

  Example code to reproduce:
  <sl-button
      aria-describedby="eye-btn-tooltip"
      fill="ghost"
      size="sm"
      icon-only
  >
      <fa-icon [icon]="faEye"></fa-icon>
  </sl-button>
  <sl-tooltip position="bottom" id="eye-btn-tooltip">
      Hide side panel
  </sl-tooltip>

### What browsers are you seeing the problem on? (only for bugs in code)

Chrome

### What operating system are you using?

Windows

### 🧢 Your product/team

ETSL

### 🎨 Your Theme(s)

Editorial Suite

**Comment by Diaan** [comment]
The issue became apparent because the icon in the button is not an sl-icon. I've made changes to that content other than text or sl-icon now also doesn't capture events (and causes the tooltip to disappear).

There is another problem with the video however, also caused by not using sl-icon:
The padding on the button is incorrect: 
<img width="49" alt="image" src="https://github.com/sl-design-system/components/assets/1351956/fdb1dedd-0b89-410f-aff4-d6f262a1deca">
We only check for `sl-icon` to add the `icon-only` property, which is used in the css to apply the correct padding.
It should look like this:
<img width="76" alt="image" src="https://github.com/sl-design-system/components/assets/1351956/3146db47-bc51-44da-9efe-0477c06577bd">
