### ISSUE TITLE
[Data grid] Add keyboard navigation

### ISSUE THREAD

**Issue by DanielleRameau** [sl-design-system/components#1526]
(see: https://www.w3.org/WAI/ARIA/apg/patterns/grid/#keyboardinteraction-settingfocusandnavigatinginsidecells)

### Patterns and documentation:
**Pagination**
When using pagination it is a good idea to let the user know there is pagination and on which page they are before "entering" the table. If a teacher opens the page with a table of all students in a class, of which they know there are 30, it might be confusing to start reading the table and have the table say it's "row 1 of 11". If the`sl-paginator-status` is placed above the table a screen reader, but also a low vision user using a magnifier will know they are not getting the full table.
compare:
![Image](https://github.com/user-attachments/assets/f19f7ef9-c1e4-4745-9358-79bc6a5425af)
With 
![Image](https://github.com/user-attachments/assets/9ff8e8ce-7366-4340-8e79-910017433a10)
Because of shadow dom boundaries i couldn't get it to work with `aria-described by` and point to the `sl-paginator-status` 

**Size and tabstops**
Be clear there is a limit on the amount of rows and tab stops per row. 300 rows, with a text field and 3 buttons means 1200 tabstops, it is better make selectable rows and make the actions bulk actions or use pagination.

```[tasklist]
### Tasks
- [ ] styling of skip links (Roald)
```

**Comment by Diaan** [comment]
Some interesting examples: https://www.w3.org/WAI/ARIA/apg/patterns/grid/examples/data-grids/

**Comment by Diaan** [comment]
- [ ] Set tab-index of all elements that are only child of cell to -1 and focus that element when the cell is active

**Comment by Diaan** [comment]
when navigating:
arrow keys: move around
enter -> go in edit mode

when in edit mode:
enter-> confirm and go to cell below, already in edit mode
esc -> exit edit mode and focus current cell
arrow keys -> like in "normal, single" input field/select

**Comment by Diaan** [comment]
![Image](https://github.com/user-attachments/assets/34e742e1-bb12-424c-975a-2c4e2716f817)
https://inclusive-components.design/data-tables/

https://adrianroselli.com/2020/02/block-links-cards-clickable-regions-etc.html#Update02

**Comment by Diaan** [comment]
research screenreader usage virtual list, both in role table and role grid

table
only data, no edit fields or selection column
clickable row
sorting
filtering

grid
interactive; edit fields, selection columns
clickable row
sorting
filtering
selection (multi select row)
all cells focusable by keyboard?

In both NVDA and voiceover there is no difference in navigating a table when it has role grid and when it has not.
Tested on https://cdpn.io/pen/debug/mdNwqNQ?authentication_hash=VGkWNpwEgaeA

https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/table_role
An element with role="table" is a static tabular structure with rows containing cells. The cells are not focusable or selectable, though widgets within individual cells of the table can be interactive.
If the interaction provides for the selection state of individual cells, if left to right and top to bottom navigation is provided, or if the user interface allows the rearranging of cell order or otherwise changing individual cell order such as through drag and drop, use grid or treegrid instead.

https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/grid_role
The grid role is a composite widget containing a collection of one or more rows with one or more cells where some or all cells in the grid are focusable by using methods of two-dimensional navigation, such as directional arrow keys.
Accessibility concerns
Even if the keyboard use is properly implemented, some users might not be aware that they have to use the arrow keys. Make sure that the functionality and interaction needed can be best achieved using the grid role.

**Comment by Diaan** [comment]
Skip table link:
Skip links work with hash links; `<a href="#content">...` and a tag that has `id="content"`. This adds the `#content` in the url and jumps to the element in the page. In frameworks/sites with a complex routing this might cause problems.
https://medium.com/@belwerks/a-quick-note-on-skip-links-in-angular-3641a0e32a7a

**Comment by DanielleRameau** [comment]
Together with Roald, I created a design for the skip link to further improve keyboard navigation in Grid (see design). For this, we introduced 3 new tokens within our new contextual token setup:

- color.background.focused (Used for the background color of navigation aids, such as skip links, to ensure contrast and visibility on focus.)
- color.text.focused (Used for the text color of navigation aids, such as skip links, when they are focused or visible.)
- color.border.focused (Used for focus rings of elements in a focus state.)

![Image](https://github.com/user-attachments/assets/ee471c90-1556-461d-bc9e-b953aa048f7a)

**Comment by Diaan** [comment]
Because the skip link is behind the table (because of the animation when showing it) I can't get the focus border to lay above the table, as it is in the design:
<img width="216" alt="Image" src="https://github.com/user-attachments/assets/4ea3f5d5-9396-4cf8-9cac-831339e788ae" />
I've moved the button a bit from the edge of the table, so the outline doesn't look so weird, poking out on the side of the table

Also, it is not possible to have a round outline on a square corner (at the bottom here):
<img width="341" alt="Image" src="https://github.com/user-attachments/assets/e955838e-00c1-4c65-a0ec-3b0c619b5a39" />
