### ISSUE TITLE
Switch label doesn't scale on text resize. 

### ISSUE THREAD

**Issue by m-siekaniec** [sl-design-system/components#1619]
### Provide a general summary of the issue here

When resizing text with [A+ Font Size Changer](https://chromewebstore.google.com/detail/a+-fontsize-changer/ckihgechpahhpompcinglebkgcdgpkil) I've noticed that the text grows only for 'Sanoma Learning' theme. For others only the container grows, but the text stays small. 

### 🤔 Expected Behavior?

Switch label should rescale for all themes; 

![image](https://github.com/user-attachments/assets/0166f323-43f9-4464-8134-c61689588349)

### 😯 Current Behavior

Works properly only for Sanoma Learning theme. 

![image](https://github.com/user-attachments/assets/e2571ebb-8130-47ec-855b-0b53fc6e432d)

### 🖥️ Steps to Reproduce

open: https://kind-plant-088739303.1.azurestaticapps.net/?path=/story/form-switch--basic
use [A+ Font Size Changer](https://chromewebstore.google.com/detail/a+-fontsize-changer/ckihgechpahhpompcinglebkgcdgpkil) and increase the text size to 200%. 
repeat for Sanoma Learning theme, and then for TEAS. 

### What browsers are you seeing the problem on? (only for bugs in code)

Chrome

### What operating system are you using?

mac

### 👤 Your name

Marcin SIekaniec

### 🧢 Your product/team

TEAS

### 🎨 Your Theme(s)

TEAS

**Comment by Diaan** [comment]
This doesn't work because the plugin just puts some css on the body tag: ![Image](https://github.com/user-attachments/assets/288f157e-9c4e-4d1c-a577-4f33787c3f2a)

All our components are webcomponents with a shadow dom and encapsulated styling; meaning the styling of the "host" doesn't effect the styling of the component. We are looking into changing the way we set the fonts for our components in https://github.com/sl-design-system/components/issues/1476

**Comment by m-siekaniec** [comment]
ah, OK thank you. For many other components the rescaling works as well, so I thought it's a reliable tool. However that would mean, that these are also considered bugs, right?
Do you test the text resize to 200% after development in SLDS team? Maybe you use some plugin/software to check it?

![image](https://github.com/user-attachments/assets/5b36f22c-c35d-4935-ba81-f1e57aa78848)
